# -*- coding: utf-8 -*-
"""cv lab3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w3rVAWjDSO11ZypFuMqVBnGbnu35KRrd
"""

import cv2
import matplotlib.pyplot as plt
import numpy as np

# function to display image
def show_comparison(original,blur3,blur5,blur7):
  plt.figure(figsize=(12,10))
  #original image
  plt.subplot(2,2,1)
  plt.imshow(original, cmap='gray')
  plt.axis('off')

  plt.subplot(2,2,2)
  plt.imshow(blur3,cmap='gray')
  plt.title('average filter(3*3)')
  plt.axis('off')

  plt.subplot(2,2,3)
  plt.imshow(blur5,cmap='gray')
  plt.title('average filter(5*5)')
  plt.axis('off')

  plt.subplot(2,2,4)
  plt.imshow(blur7,cmap='gray')
  plt.title('average filter(7*7)')
  plt.axis('off')

  plt.tight_layout()
  plt.show()

img = cv2.imread('/content/img2.jpg', 0)
if img is None:
  print('Error: Image "//content/img2.jpg" not found or could not be loaded in this cell.')
else:
  kernal_3x3=np.ones((3,3),np.float32)/9
  kernal_5x5=np.ones((5,5),np.float32)/25
  kernal_7x7=np.ones((7,7),np.float32)/49

  blur_3x3=cv2.filter2D(img,-1,kernal_3x3)
  blur_5x5=cv2.filter2D(img,-1,kernal_5x5)
  blur_7x7=cv2.filter2D(img,-1,kernal_7x7)
  show_comparison(img, blur_3x3, blur_5x5, blur_7x7)

import numpy as np
import matplotlib.pyplot as plt

kernel = np.ones((15,15)) * 1/225
k_s = 15


m = img.shape[0]
n = img.shape[1]


filtered_img = np.zeros((m - k_s + 1, n - k_s + 1), dtype=img.dtype)


for i in range(m - k_s + 1):
   for j in range(n - k_s + 1):
      image_region = img[i:i+k_s, j:j+k_s]

      filtered_img[i, j] = np.sum(kernel * image_region)


plt.imshow(filtered_img, cmap='gray')
plt.title(f'Manually Filtered Image ({k_s}x{k_s})')
plt.axis('off')
plt.show()

import numpy as np
import matplotlib.pyplot as plt

def manual_convolve(image, kernel_size):



    k = kernel_size
    kernel = np.ones((k, k), dtype=np.float32) / (k * k)

    m, n = image.shape
    #  Initialize the output array 'filtered' before using it in the loop
    filtered = np.zeros((m - k + 1, n - k + 1), dtype=np.uint8)

    for i in range(m - k + 1):
        for j in range(n - k + 1):
            region = image[i:i+k, j:j+k]
            filtered[i, j] = np.sum(region * kernel)

    return filtered

# Calculate manual filtering for four different kernel sizes
man_blur_3 = manual_convolve(img, 3)
man_blur_5 = manual_convolve(img, 5)
man_blur_7 = manual_convolve(img, 7)
man_blur_15 = manual_convolve(img, 15)

# Display the results in a grid
plt.figure(figsize=(15, 12))

plt.subplot(2, 2, 1)
plt.imshow(man_blur_3, cmap='gray')
plt.title('Manual Blur (3x3)')
plt.axis('off')

plt.subplot(2, 2, 2)
plt.imshow(man_blur_5, cmap='gray')
plt.title('Manual Blur (5x5)')
plt.axis('off')

plt.subplot(2, 2, 3)
plt.imshow(man_blur_7, cmap='gray')
plt.title('Manual Blur (7x7)')
plt.axis('off')

plt.subplot(2, 2, 4)
plt.imshow(man_blur_15, cmap='gray')
plt.title('Manual Blur (15x15)')
plt.axis('off')

plt.tight_layout()
plt.show()